### PR TITLE
Development

### PR DESCRIPTION
**Pull request by kelvin8773**
Finish Unit Test Project.

### CODE REVIEW

**Review by JamesOkunlade — CHANGES_REQUESTED** [review]
Hello @kelvin8773 , @DenisCuencaBrex , 

Good work writing tests for your tic-tac-toe game.

I encountered errors while running your tests though. Have you tested to confirm test are running successfully before requesting for review? 


image

Please check again and submit for review.

**Comment by kelvin8773** [comment]
finalize the unit test, refactor unit test and game's code to make it more test able.
Remove the necessary the need of "colorize" plug-in support in unit test.

**Comment by kelvin8773** [comment]
Hi, James,
We have remove the require "colorize" plug-in the unit-test, I think the unit test will work, but in any case if doesn't, please try "gem install colorize", thanks and sorry for the inconvenience!

**Comment by azdrenymeri** [comment]
### Hello @kelvin8773 and @DenisCuencaBrex :medal_military: 
#### Good job 
#### I run the tests and all of them are passing 
#### No further requests from my side you can go ahead and merge it

**Pull request merged**
